# Generated by Django 4.2.15 on 2024-09-05 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0006_hassasiyetturu_ilackategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 5, 14, 31, 40, 567298, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Hastalik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('ilaclar', models.ManyToManyField(blank=True, to='appname.ilac')),
            ],
        ),
    ]
