# Generated by Django 4.2.15 on 2024-10-24 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_form_slug_hastalik_slug_ilac_slug_ilackategori_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 17, 4, 55, 251010, tzinfo=datetime.timezone.utc)),
        ),
    ]
