# Generated by Django 4.2.15 on 2024-09-06 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_alter_passwordresetcode_expires_at_hastalik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastalik',
            name='ilaclar',
        ),
        migrations.AddField(
            model_name='ilac',
            name='hastaliklar',
            field=models.ManyToManyField(related_name='ilaclar', to='appname.hastalik'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 11, 38, 47, 216853, tzinfo=datetime.timezone.utc)),
        ),
    ]
