# Generated by Django 4.2.15 on 2024-10-24 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_product_slug_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 17, 38, 7, 229143, tzinfo=datetime.timezone.utc)),
        ),
    ]
