# Generated by Django 4.2.15 on 2024-09-06 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0008_remove_hastalik_ilaclar_ilac_hastaliklar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 16, 16, 54, 576961, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='YasDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doz', models.CharField(blank=True, max_length=200, null=True)),
                ('min_yas', models.IntegerField()),
                ('maks_yas', models.IntegerField()),
                ('kullanim_uyarisi', models.CharField(blank=True, max_length=300, null=True)),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.ilac')),
            ],
        ),
    ]
