# Generated by Django 4.2.15 on 2024-11-05 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 5, 13, 39, 41, 602059, tzinfo=datetime.timezone.utc)),
        ),
    ]
