# Generated by Django 4.2.15 on 2024-12-23 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0011_contact_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilac',
            name='kullanim_uyarisi',
        ),
        migrations.AddField(
            model_name='ilac',
            name='baslik',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ilac',
            name='ne_icin_kullanilir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ilac',
            name='nedir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 12, 19, 17, 179378, tzinfo=datetime.timezone.utc)),
        ),
    ]
