# Generated by Django 4.2.15 on 2024-09-08 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_alter_passwordresetcode_expires_at_explanation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Explanation',
            new_name='ExplanationDoz',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 13, 29, 25, 261115, tzinfo=datetime.timezone.utc)),
        ),
    ]
