# Generated by Django 4.2.15 on 2024-12-23 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0012_remove_ilac_kullanim_uyarisi_ilac_baslik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 23, 15, 7, 37, 405575, tzinfo=datetime.timezone.utc)),
        ),
    ]
