# Generated by Django 4.2.15 on 2024-09-08 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0013_rename_explanation_explanationdoz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilac',
            name='kontsantrasyon_mg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='ilac',
            name='kontsantrasyon_ml',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 15, 5, 8, 814588, tzinfo=datetime.timezone.utc)),
        ),
    ]
