# Generated by Django 4.2.15 on 2024-09-08 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_ilac_kontsantrasyon_mg_ilac_kontsantrasyon_ml_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilodoz',
            name='maksimum_gunluk_doz',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 16, 4, 17, 709994, tzinfo=datetime.timezone.utc)),
        ),
    ]
