# Generated by Django 4.2.15 on 2024-12-27 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 13, 14, 59, 141047, tzinfo=datetime.timezone.utc)),
        ),
    ]
