# Generated by Django 4.2.15 on 2025-01-09 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0015_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ne_icin_kullanilir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='nedir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 15, 33, 5, 876052, tzinfo=datetime.timezone.utc)),
        ),
    ]
