# Generated by Django 4.2.15 on 2024-09-08 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0015_remove_kilodoz_maksimum_gunluk_doz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kilodoz',
            name='maksimum_gunluk_doz',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 16, 50, 42, 881824, tzinfo=datetime.timezone.utc)),
        ),
    ]
