# Generated by Django 4.2.15 on 2025-02-05 01:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0016_product_ne_icin_kullanilir_product_nedir_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationdoz',
            name='check_uyari',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hatirlatici',
            name='kuvvet',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 5, 1, 44, 48, 833611, tzinfo=datetime.timezone.utc)),
        ),
    ]
