# Generated by Django 4.2.15 on 2025-08-15 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0017_explanationdoz_check_uyari_alter_hatirlatici_kuvvet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 15, 5, 8, 40, 8135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cover_photo')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='appname.blogs')),
            ],
        ),
    ]
