# Generated by Django 4.2.15 on 2024-09-09 14:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0017_alter_kilodoz_maksimum_gunluk_doz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 9, 14, 39, 54, 160437, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HatalikYasDoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doz', models.CharField(blank=True, max_length=200, null=True)),
                ('min_yas', models.IntegerField()),
                ('maks_yas', models.IntegerField()),
                ('hastaliklar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikyasdoz', to='appname.hastalik')),
                ('ilac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.ilac')),
            ],
        ),
    ]
