# Generated by Django 4.2.15 on 2025-08-16 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0018_alter_passwordresetcode_expires_at_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='explanations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 2, 54, 50, 884209, tzinfo=datetime.timezone.utc)),
        ),
    ]
