# Generated by Django 4.2.15 on 2024-09-10 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0019_alter_passwordresetcode_expires_at_hastalikkilodoz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 11, 0, 18, 632145, tzinfo=datetime.timezone.utc)),
        ),
    ]
