# Generated by Django 4.2.15 on 2025-08-16 15:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0019_blogs_explanations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 16, 13, 31, 906928, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StoryCoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='story_cover_photo')),
                ('order', models.IntegerField(default=0)),
                ('story_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_cover_photo', to='appname.storytitle')),
            ],
        ),
    ]
