# Generated by Django 4.2.15 on 2025-08-16 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0020_storytitle_alter_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storycoverphoto',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storytitle',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 16, 16, 22, 22, 675264, tzinfo=datetime.timezone.utc)),
        ),
    ]
