# Generated by Django 4.2.15 on 2024-09-10 11:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0020_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hastalikkilodoz',
            name='hastaliklar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hastalikkilodoz', to='appname.hastalik'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 11, 26, 17, 225890, tzinfo=datetime.timezone.utc)),
        ),
    ]
