# Generated by Django 4.2.15 on 2025-08-19 21:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0021_storycoverphoto_is_status_storytitle_is_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 21, 51, 11, 277239, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='storyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='story_content_image')),
                ('order', models.IntegerField(default=0)),
                ('is_status', models.BooleanField(default=True)),
                ('story_cover_Photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_content', to='appname.storycoverphoto')),
            ],
        ),
    ]
