# Generated by Django 4.2.15 on 2025-08-19 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0022_alter_passwordresetcode_expires_at_storycontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 19, 21, 55, 21, 646371, tzinfo=datetime.timezone.utc)),
        ),
    ]
