# Generated by Django 4.2.15 on 2024-09-10 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0022_alter_passwordresetcode_expires_at_artankilodoz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artankilodoz',
            old_name='weight_threshold_for_calculation',
            new_name='threshold_weight',
        ),
        migrations.RemoveField(
            model_name='artankilodoz',
            name='dose_for_specified_weight_and_below',
        ),
        migrations.AddField(
            model_name='artankilodoz',
            name='threshold_weight_min_dose',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 13, 23, 44, 524580, tzinfo=datetime.timezone.utc)),
        ),
    ]
