# Generated by Django 4.2.15 on 2024-09-10 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0023_rename_weight_threshold_for_calculation_artankilodoz_threshold_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artankilodoz',
            name='threshold_weight_max_dose',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 10, 13, 24, 26, 631486, tzinfo=datetime.timezone.utc)),
        ),
    ]
