# Generated by Django 4.2.15 on 2025-08-20 22:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0023_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 23, 13, 14, 445263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanations', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_status', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_content', to='appname.blogs')),
            ],
        ),
    ]
