# Generated by Django 4.2.15 on 2025-08-20 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0024_alter_passwordresetcode_expires_at_blogcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='is_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 20, 23, 20, 42, 162155, tzinfo=datetime.timezone.utc)),
        ),
    ]
