# Generated by Django 4.2.15 on 2025-08-22 02:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0025_blogs_is_status_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcontent',
            name='baslik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 2, 46, 27, 798357, tzinfo=datetime.timezone.utc)),
        ),
    ]
