# Generated by Django 4.2.15 on 2025-09-30 15:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0026_blogcontent_baslik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 15, 18, 49, 635525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StoryContentRecorded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='appname.storycontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_content_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='appname.storycontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_content_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
