# Generated by Django 4.2.15 on 2025-09-30 22:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0027_alter_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 30, 22, 32, 26, 843742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='BlogContentRecorded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='appname.blogcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_content_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='appname.blogcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_content_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
