# Generated by Django 4.2.15 on 2024-09-11 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0029_alter_passwordresetcode_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hastalikhemyasahemkiloyabagliazalandoz',
            name='maksimum_anlik_doz',
        ),
        migrations.RemoveField(
            model_name='hastalikhemyasahemkiloyabagliazalandoz',
            name='maksimum_gunluk_doz',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 11, 18, 16, 26, 480683, tzinfo=datetime.timezone.utc)),
        ),
    ]
