# Generated by Django 4.2.15 on 2024-09-12 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0033_remove_hastalikhemyasahemkiloyabagliartandoz_maksimum_gunluk_doz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artankilodoz',
            name='maksimum_gunluk_doz',
        ),
        migrations.RemoveField(
            model_name='hastalikartankilodoz',
            name='maksimum_gunluk_doz',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 16, 33, 376187, tzinfo=datetime.timezone.utc)),
        ),
    ]
