# Generated by Django 4.2.15 on 2024-09-12 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0035_remove_hastalikkilodoz_maksimum_gunluk_doz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kilodoz',
            name='maksimum_gunluk_doz',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 13, 32, 51, 874980, tzinfo=datetime.timezone.utc)),
        ),
    ]
