# Generated by Django 4.2.15 on 2024-09-12 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0037_product_productcategory_supplement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.productcategory'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='supplement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.supplement'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 12, 16, 31, 19, 621661, tzinfo=datetime.timezone.utc)),
        ),
    ]
