# Generated by Django 4.2.15 on 2024-09-15 14:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0038_product_product_category_productcategory_supplement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hatirlatici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('form', models.CharField(blank=True, max_length=50, null=True)),
                ('kuvvet', models.CharField(blank=True, max_length=50, null=True)),
                ('baslangic_tarihi', models.DateTimeField(blank=True, null=True)),
                ('bitis_tarihi', models.DateTimeField(blank=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='artankilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='azalankilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='explanationdoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hastalikartankilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hastalikazalankilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hastalikhemyasahemkiloyabagliartandoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hastalikhemyasahemkiloyabagliazalandoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hastalikkilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='hatalikyasdoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='kilodoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 14, 55, 57, 964135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='yasdoz',
            name='ilac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appname.ilac'),
        ),
        migrations.CreateModel(
            name='HatirlaticiSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField()),
                ('hatirlatici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_saat', to='appname.hatirlatici')),
            ],
        ),
    ]
