# Generated by Django 4.2.15 on 2024-09-15 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0039_hatirlatici_alter_artankilodoz_ilac_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatirlaticisaati',
            name='saat',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 15, 4, 54, 514374, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Bildirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField(blank=True, null=True)),
                ('durum', models.BooleanField(default=False)),
                ('hatirlatici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hatirlatici_bildirim', to='appname.hatirlatici')),
            ],
        ),
    ]
