# Generated by Django 4.2.15 on 2024-09-15 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0040_alter_hatirlaticisaati_saat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hatirlatici',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hatirlatici',
            name='bitis_tarihi',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 15, 54, 19, 772932, tzinfo=datetime.timezone.utc)),
        ),
    ]
