# Generated by Django 4.2.15 on 2024-09-22 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0043_form_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='form_img'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 17, 26, 16, 876187, tzinfo=datetime.timezone.utc)),
        ),
    ]
