# Generated by Django 4.2.15 on 2024-09-24 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0044_form_img_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hatirlaticisaati',
            name='is_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 14, 50, 7, 904635, tzinfo=datetime.timezone.utc)),
        ),
    ]
