# Generated by Django 4.2.15 on 2024-09-24 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0046_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hatirlaticisaati',
            name='is_status',
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 17, 15, 14, 248080, tzinfo=datetime.timezone.utc)),
        ),
    ]
