# Generated by Django 4.2.15 on 2024-09-25 17:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0047_remove_hatirlaticisaati_is_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilac',
            name='ilac_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appname.form'),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 17, 50, 19, 508668, tzinfo=datetime.timezone.utc)),
        ),
    ]
