# Generated by Django 4.2.15 on 2024-09-25 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0048_ilac_ilac_form_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 18, 23, 52, 80006, tzinfo=datetime.timezone.utc)),
        ),
    ]
