# Generated by Django 4.2.15 on 2024-09-25 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0050_alter_ilackategori_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilac',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 19, 1, 17, 937664, tzinfo=datetime.timezone.utc)),
        ),
    ]
