# Generated by Django 4.2.15 on 2024-09-25 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0051_alter_ilac_name_alter_passwordresetcode_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilac',
            name='etken_madde',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 25, 19, 1, 57, 252709, tzinfo=datetime.timezone.utc)),
        ),
    ]
